export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[var(--bg-primary)] py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold text-[var(--text-primary)] mb-8">Privacy Policy</h1>

        <div className="space-y-6 text-[var(--text-secondary)]">
          <p className="text-sm text-[var(--text-tertiary)]">Last updated: January 28, 2025</p>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">1. Introduction</h2>
            <p>
              Tenex (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains
              how we collect, use, disclose, and safeguard your information when you use our AI-powered calendar
              assistant service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">2. Information We Collect</h2>

            <h3 className="text-lg font-medium text-[var(--text-primary)]">2.1 Information from Google</h3>
            <p>When you sign in with Google and grant permissions, we access:</p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li><strong>Google Calendar data:</strong> Event titles, times, attendees, and descriptions to provide scheduling assistance</li>
              <li><strong>Gmail data:</strong> Email addresses and message content (only when you use email features) to draft and send scheduling-related communications</li>
              <li><strong>Profile information:</strong> Your name, email address, and profile picture for account identification</li>
            </ul>

            <h3 className="text-lg font-medium text-[var(--text-primary)] mt-4">2.2 Information We Store</h3>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Account information (name, email, profile picture)</li>
              <li>OAuth tokens (encrypted) to maintain your Google connection</li>
              <li>Your preferences and settings</li>
              <li>Email suggestions generated by the AI (until sent or dismissed)</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">3. How We Use Your Information</h2>
            <p>We use the information we collect to:</p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Provide personalized calendar insights and scheduling recommendations</li>
              <li>Generate AI-powered daily briefings about your schedule</li>
              <li>Draft email communications on your behalf (sent only with your approval)</li>
              <li>Analyze your time usage patterns to provide productivity insights</li>
              <li>Improve and optimize the Service</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">4. Google API Services User Data Policy</h2>
            <p>
              Our use and transfer of information received from Google APIs adheres to the
              <a
                href="https://developers.google.com/terms/api-services-user-data-policy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[var(--text-primary)] underline ml-1"
              >
                Google API Services User Data Policy
              </a>, including the Limited Use requirements.
            </p>
            <p className="mt-2">Specifically:</p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>We only request access to data necessary for the Service&apos;s functionality</li>
              <li>We do not sell your Google user data to third parties</li>
              <li>We do not use your Google user data for advertising purposes</li>
              <li>We do not allow humans to read your data unless required for security purposes, legal compliance, or with your explicit consent</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">5. AI Processing</h2>
            <p>
              We use Claude, an AI assistant by Anthropic, to process your calendar and email data to generate
              insights and suggestions. Your data is processed in real-time and is not stored by the AI service
              beyond the immediate request. We do not use your data to train AI models.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">6. Data Sharing</h2>
            <p>We do not sell, trade, or rent your personal information. We may share your information only in these circumstances:</p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li><strong>Service providers:</strong> Third-party services that help us operate (e.g., hosting, AI processing)</li>
              <li><strong>Legal requirements:</strong> When required by law or to protect our rights</li>
              <li><strong>With your consent:</strong> When you explicitly authorize sharing</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">7. Data Security</h2>
            <p>
              We implement industry-standard security measures to protect your data, including:
            </p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>Encryption of data in transit (HTTPS/TLS)</li>
              <li>Encryption of sensitive data at rest</li>
              <li>Secure OAuth 2.0 authentication</li>
              <li>Regular security assessments</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">8. Data Retention</h2>
            <p>
              We retain your account information for as long as your account is active. Calendar and email data
              is accessed in real-time from Google and is not permanently stored on our servers. Email suggestions
              are retained until sent or dismissed by you.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">9. Your Rights</h2>
            <p>You have the right to:</p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li><strong>Access:</strong> Request a copy of the data we hold about you</li>
              <li><strong>Correction:</strong> Request correction of inaccurate data</li>
              <li><strong>Deletion:</strong> Request deletion of your account and associated data</li>
              <li><strong>Revoke access:</strong> Disconnect Google permissions at any time through your Google Account settings</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">10. Revoking Access</h2>
            <p>
              You can revoke Tenex&apos;s access to your Google data at any time by visiting your
              <a
                href="https://myaccount.google.com/permissions"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[var(--text-primary)] underline ml-1"
              >
                Google Account permissions page
              </a>.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">11. Children&apos;s Privacy</h2>
            <p>
              The Service is not intended for children under 13 years of age. We do not knowingly collect
              personal information from children under 13.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">12. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of any changes by posting
              the new Privacy Policy on this page and updating the &quot;Last updated&quot; date.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--text-primary)]">13. Contact Us</h2>
            <p>
              If you have questions about this Privacy Policy or our data practices, please contact us at:
            </p>
            <p className="mt-2">
              Email: privacy@tenex.app
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-[var(--border-medium)]">
          <a
            href="/login"
            className="text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
          >
            &larr; Back to Login
          </a>
        </div>
      </div>
    </div>
  );
}
